export const countries = [
  { code: 'IN', name: 'India', currency: 'INR', flag: '🇮🇳' },
  { code: 'US', name: 'United States', currency: 'USD', flag: '🇺🇸' },
  { code: 'GB', name: 'United Kingdom', currency: 'GBP', flag: '🇬🇧' },
  { code: 'CA', name: 'Canada', currency: 'CAD', flag: '🇨🇦' },
  { code: 'AU', name: 'Australia', currency: 'AUD', flag: '🇦🇺' },
  { code: 'NZ', name: 'New Zealand', currency: 'NZD', flag: '🇳🇿' },
  { code: 'SG', name: 'Singapore', currency: 'SGD', flag: '🇸🇬' },
  { code: 'AE', name: 'United Arab Emirates', currency: 'AED', flag: '🇦🇪' },
  { code: 'SA', name: 'Saudi Arabia', currency: 'SAR', flag: '🇸🇦' },
  { code: 'ZA', name: 'South Africa', currency: 'ZAR', flag: '🇿🇦' },
  { code: 'DE', name: 'Germany', currency: 'EUR', flag: '🇩🇪' },
  { code: 'FR', name: 'France', currency: 'EUR', flag: '🇫🇷' },
  { code: 'IT', name: 'Italy', currency: 'EUR', flag: '🇮🇹' },
  { code: 'ES', name: 'Spain', currency: 'EUR', flag: '🇪🇺' },
  { code: 'NL', name: 'Netherlands', currency: 'EUR', flag: '🇳🇱' },
  { code: 'CH', name: 'Switzerland', currency: 'CHF', flag: '🇨🇭' },
  { code: 'NO', name: 'Norway', currency: 'NOK', flag: '🇳🇴' },
  { code: 'SE', name: 'Sweden', currency: 'SEK', flag: '🇸🇪' },
  { code: 'JP', name: 'Japan', currency: 'JPY', flag: '🇯🇵' },
  { code: 'KR', name: 'South Korea', currency: 'KRW', flag: '🇰🇷' },
  { code: 'MX', name: 'Mexico', currency: 'MXN', flag: '🇲🇽' },
  { code: 'BR', name: 'Brazil', currency: 'BRL', flag: '🇧🇷' },
  { code: 'HK', name: 'Hong Kong', currency: 'HKD', flag: '🇭🇰' },
  { code: 'MY', name: 'Malaysia', currency: 'MYR', flag: '🇲🇾' },
] as const;

// Reference defaults only. Indirect tax can depend on product, province/state,
// taxpayer status and filing period; unsupported jurisdictions intentionally use 0
// here so the UI displays “—” instead of implying a verified tax rate.
export const taxData = {
  IN: { indirectName: 'GST', standardIndirect: 18, incomeBrackets: [] },
  US: { indirectName: 'Sales Tax', standardIndirect: 0, incomeBrackets: [] },
  GB: { indirectName: 'VAT', standardIndirect: 20, incomeBrackets: [] },
  CA: { indirectName: 'GST/HST', standardIndirect: 5, incomeBrackets: [] },
  AU: { indirectName: 'GST', standardIndirect: 10, incomeBrackets: [] },
  NZ: { indirectName: 'GST', standardIndirect: 15, incomeBrackets: [] },
  SG: { indirectName: 'GST', standardIndirect: 9, incomeBrackets: [] },
  AE: { indirectName: 'VAT', standardIndirect: 5, incomeBrackets: [] },
  SA: { indirectName: 'VAT', standardIndirect: 15, incomeBrackets: [] },
  ZA: { indirectName: 'VAT', standardIndirect: 15, incomeBrackets: [] },
  DE: { indirectName: 'VAT', standardIndirect: 19, incomeBrackets: [] },
  FR: { indirectName: 'VAT', standardIndirect: 20, incomeBrackets: [] },
  IT: { indirectName: 'VAT', standardIndirect: 22, incomeBrackets: [] },
  ES: { indirectName: 'VAT', standardIndirect: 21, incomeBrackets: [] },
  NL: { indirectName: 'VAT', standardIndirect: 21, incomeBrackets: [] },
  CH: { indirectName: 'VAT', standardIndirect: 8.1, incomeBrackets: [] },
  NO: { indirectName: 'VAT', standardIndirect: 25, incomeBrackets: [] },
  SE: { indirectName: 'VAT', standardIndirect: 25, incomeBrackets: [] },
  JP: { indirectName: 'Consumption Tax', standardIndirect: 10, incomeBrackets: [] },
  KR: { indirectName: 'VAT', standardIndirect: 10, incomeBrackets: [] },
  MX: { indirectName: 'VAT', standardIndirect: 16, incomeBrackets: [] },
  BR: { indirectName: 'Consumption taxes', standardIndirect: 0, incomeBrackets: [] },
  HK: { indirectName: 'No broad VAT/GST', standardIndirect: 0, incomeBrackets: [] },
  MY: { indirectName: 'SST', standardIndirect: 0, incomeBrackets: [] },
} as const;

export type CountryCode = keyof typeof taxData;
